// Code generated by "stringer -type=Level"; DO NOT EDIT

package mylog

import "fmt"

const (
	_Level_name_0 = "ERRORDEBUG"
	_Level_name_1 = "FATAL"
	_Level_name_2 = "INFO"
	_Level_name_3 = "WARN"
)

var (
	_Level_index_0 = [...]uint8{0, 5, 10}
	_Level_index_1 = [...]uint8{0, 5}
	_Level_index_2 = [...]uint8{0, 4}
	_Level_index_3 = [...]uint8{0, 4}
)

func (i Level) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Level_name_0[_Level_index_0[i]:_Level_index_0[i+1]]
	case i == 4:
		return _Level_name_1
	case i == 8:
		return _Level_name_2
	case i == 16:
		return _Level_name_3
	default:
		return fmt.Sprintf("Level(%d)", i)
	}
}
